<div style="border: 2px solid #333; padding: 20px; max-width: 600px; font-family: Arial, sans-serif; background-color: #f9f9f9; text-align: center;">
  <h2 style="color: #222;">Partner with SUMAS Chronicle</h2>
  <p style="font-size: 16px; color: #555;">
    At <strong>SUMAS Chronicle</strong>, our mission is to deliver accurate, insightful, and thought-provoking stories that inform and inspire our audience. We believe in the power of storytelling to shape perspectives and foster a more informed society.
  </p>
  <p style="font-size: 16px; color: #555;">
    We welcome both individual supporters and corporate partners to join us in advancing quality journalism. By sponsoring SUMAS Chronicle, you become a vital part of this mission and gain meaningful visibility among our engaged audience.
  </p>
  <a href="tel:+2348137575389" style="display: inline-block; margin-top: 15px; padding: 12px 25px; background-color: #222; color: #fff; text-decoration: none; font-weight: bold; border-radius: 5px;">
    Click to Sponsor
  </a>
  <p style="font-size: 14px; color: #777; margin-top: 10px;">
    Contact us directly at <a href="tel:+2348137575389" style="color: #222; text-decoration: none;">+2348137575389</a>
  </p>
</div>
